### ISSUE TITLE
Broken link "How to Build Cardano SL and Daedalus from Source Code"

### ISSUE THREAD

**Issue by p-alik** [input-output-hk/cardanodocs.com#71]
Please replace the target of aforementioned link in [2017-01-04-installation.md](../blob/master/_docs/2017-01-04-installation.md) by https://github.com/input-output-hk/cardano-sl/blob/develop/docs/how-to/build-cardano-sl-and-daedalus-from-source-code.md or like in [Cardano SL and Daedalus Bridge](https://github.com/input-output-hk/cardano-sl/tree/develop#cardano-sl-and-daedalus-bridge) section by 
https://cardanodocs.com/for-contributors/building-from-source/

**Comment by denisshevchenko** [comment]
Thanks! Fixed.
