### ISSUE TITLE
404s for certain URLs ending with /

### ISSUE THREAD

**Issue by gufmar** [input-output-hk/cardanodocs.com#97]
it looks like certain former working URLs does return an http.404 now

I pointed some guys on facebook to cardanodocs sl api.

They weren’t able to access it before because they found and tried to use the links at 
https://forum.cardano.org/t/how-to-use-postman-to-access-the-cardano-api-on-debian-gnu-linux-sid/4269
and
https://forum.cardano.org/t/rest-apis-availability/9058

The problem with this links is the final / that seems to have worked as valid URLs the time when these messages were posted on the forum.
(I reported this also to the forum admins but it would be better to fix it on this side, and eventually look for a way to monitor extraordinary amounts of 404s)

**Comment by jonathancross** [comment]
The link in question works for me: https://cardanodocs.com/technical/wallet/api/

If you agree, please close this  :-)

**Comment by gufmar** [comment]
never got a notification but seems working now.
