### ISSUE TITLE
Travis CI doesn't seem to be running for Explorer Docs

### ISSUE THREAD

**Issue by codybutz** [input-output-hk/cardanodocs.com#98]
I was looking over the documentation for the Cardano Explorer API and found it references an API route: `GET /api/genesis/address/pages` [API Link](https://cardanodocs.com/technical/explorer/api/#path--api-genesis-address-pages) no longer exists in the Explorer API and seems to have been replaced with: `GET /api/genesis/address`

After looking over the documentation it seems that Travis CI was used to regenerate the Explorer documentation, however it hasn't ran since Sept 27th, 2017. This is just an assumption, if I am looking in the wrong place let me know.

Thanks!

**Comment by ksaric** [comment]
@codybutz You seem to be right. It seems that the old repository has that API defined - https://github.com/input-output-hk/cardano-sl-explorer/blob/master/src/Pos/Explorer/Web/Api.hs

We did merge the repository and there was a rule about running the API build only on the `master` branch so it could be that something went wrong. 
We will take a look at it, thanks for reporting the issue.

https://iohk.myjetbrains.com/youtrack/issue/CSE-262

**Comment by codybutz** [comment]
@ksaric Thanks! Keep up the awesome work! Really love what you guys are building here.

**Comment by ksaric** [comment]
Thanks for the feedback @codybutz, @CodiePP fixed it here - https://github.com/input-output-hk/cardanodocs.com/pull/100
